name: framehub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  device_preview: ^1.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_cloud_firestore: ^5.4.4
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true