// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWORven7u_UC1zKLpcM2N1lysz93m8n4o',
    appId: '1:479149265486:android:e35f53e1e14ecc49b2a91f',
    messagingSenderId: '479149265486',
    projectId: 'app-frame-hub',
    storageBucket: 'app-frame-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDDFbdg77T7OYryaDDmsvBc55KEicOMw',
    appId: '1:479149265486:ios:ef7ecdb27988c783b2a91f',
    messagingSenderId: '479149265486',
    projectId: 'app-frame-hub',
    storageBucket: 'app-frame-hub.firebasestorage.app',
    iosBundleId: 'com.example.framehub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqEANhL8_CjiwVUyociUse7FL0MVYQo2U',
    appId: '1:479149265486:web:537bd7d987bee205b2a91f',
    messagingSenderId: '479149265486',
    projectId: 'app-frame-hub',
    authDomain: 'app-frame-hub.firebaseapp.com',
    storageBucket: 'app-frame-hub.firebasestorage.app',
  );

}